# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Tested-ClassDBI
version:      0.13
version_from: lib/HTML/Tested/ClassDBI.pm
installdirs:  site
requires:
    Class::DBI::Pg::More:          0.02
    File::MMagic:                  
    HTML::Tested:                  0.22
    Test::TempDatabase:            

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
